### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by DVP-Devo** [protiumx/dev.resume#1]
Thanks for the template!
It didn't compile for me due to missing fonts:
MavenPro-SemiBold wasn't in the folder.
fonts/ello/ isn't on the repo.

I changed resume.cls as follows to get it to compile:

`\usepackage{fontspec}
\setmainfont[Color=primary, Path = fonts/maven-pro/, BoldFont=MavenPro-Bold]{MavenPro-Regular}`

`\newcommand{\namesection}[2]{
\centering{
\fontsize{28pt}{60pt}
\fontspec[Path = fonts/source-code/]{SourceCodePro-ExtraLight}\selectfont #1
\color{links}
\fontspec[Path = fonts/source-code/]{SourceCodePro-Light}\selectfont #2`

**Comment by protiumx** [comment]
Hi! Thanks for the catch, I didn't realize I didn't upload the correct font. I'll update it soon.
What tool are you using for compiling it?
Have you tried with https://www.overleaf.com/?

**Comment by DVP-Devo** [comment]
All good, and thanks for hosting the template.
Yeah I tried compiling with overleaf originally.
I just downloaded the latest repo zip and it compiled in overleaf this time with no problems!
Cheers
